/**
 * Theme Presets — predefined theme configurations for simulations.
 *
 * Each preset is a flat Record<string, string> matching setting keys
 * used in simulation_settings (category='design').
 */

import type { SimulationTheme } from '../types/index.js';

export type ThemePresetName =
  | 'brutalist'
  | 'sunless-sea'
  | 'solarpunk'
  | 'cyberpunk'
  | 'nordic-noir'
  | 'deep-space-horror'
  | 'arc-raiders'
  | 'illuminated-literary'
  | 'deep-fried-horror';

export const THEME_PRESETS: Record<ThemePresetName, Record<string, string>> = {
  brutalist: {
    color_primary: '#000000',
    color_primary_hover: '#1a1a1a',
    color_primary_active: '#333333',
    color_secondary: '#3b82f6',
    color_accent: '#d97706',
    color_background: '#ffffff',
    color_surface: '#f5f5f5',
    color_surface_sunken: '#e5e5e5',
    color_surface_header: '#fafafa',
    color_text: '#0a0a0a',
    color_text_secondary: '#525252',
    color_text_muted: '#737373',
    color_border: '#000000',
    color_border_light: '#d4d4d4',
    color_danger: '#dc2626',
    color_success: '#16a34a',
    color_primary_bg: '#f3f4f6',
    color_info_bg: '#eff6ff',
    color_danger_bg: '#fef2f2',
    color_success_bg: '#f0fdf4',
    color_warning_bg: '#fffbeb',
    font_heading: "'Oswald', 'Arial Narrow', sans-serif",
    font_body: 'system-ui, -apple-system, sans-serif',
    font_mono: "SF Mono, Monaco, Inconsolata, 'Roboto Mono', monospace",
    heading_weight: '900',
    heading_transform: 'uppercase',
    heading_tracking: '1px',
    font_base_size: '16px',
    border_radius: '0',
    border_width: '3px',
    border_width_default: '2px',
    shadow_style: 'offset',
    shadow_color: '#000000',
    hover_effect: 'translate',
    animation_speed: '1',
    animation_easing: 'ease',
    text_inverse: '#ffffff',
    card_frame_texture: 'none',
    card_frame_nameplate: 'terminal',
    card_frame_corners: 'none',
    card_frame_foil: 'holographic',
  },

  'sunless-sea': {
    color_primary: '#0d7377',
    color_primary_hover: '#0a5c5f',
    color_primary_active: '#084a4d',
    color_secondary: '#00e5cc',
    color_accent: '#f4a261',
    color_background: '#0a1628',
    color_surface: '#0f2236',
    color_surface_sunken: '#081320',
    color_surface_header: '#0d1d30',
    color_text: '#e8ede9',
    color_text_secondary: '#90aa9c',
    color_text_muted: '#82a898',
    color_border: '#1a3a4a',
    color_border_light: '#0f2a3a',
    color_danger: '#e74c3c',
    color_success: '#27ae60',
    color_primary_bg: '#061a1e',
    color_info_bg: '#0d2a38',
    color_danger_bg: '#2d1520',
    color_success_bg: '#0d2a1e',
    color_warning_bg: '#2a2210',
    font_heading: "'Cormorant Garamond', Georgia, serif",
    font_body: "'Segoe UI', Roboto, sans-serif",
    font_mono: "SF Mono, Monaco, Inconsolata, 'Roboto Mono', monospace",
    heading_weight: '700',
    heading_transform: 'none',
    heading_tracking: '0.05em',
    font_base_size: '16px',
    border_radius: '6px',
    border_width: '1px',
    border_width_default: '1px',
    shadow_style: 'glow',
    shadow_color: '#00e5cc',
    hover_effect: 'glow',
    animation_speed: '1.5',
    animation_easing: 'ease-in-out',
    text_inverse: '#e8ede9',
    card_frame_texture: 'filigree',
    card_frame_nameplate: 'banner',
    card_frame_corners: 'tentacles',
    card_frame_foil: 'aquatic',
  },

  solarpunk: {
    color_primary: '#16a34a',
    color_primary_hover: '#15803d',
    color_primary_active: '#166534',
    color_secondary: '#b45309',
    color_accent: '#e11d48',
    color_background: '#fefce8',
    color_surface: '#fffbeb',
    color_surface_sunken: '#fef9c3',
    color_surface_header: '#fefdf0',
    color_text: '#1a2e05',
    color_text_secondary: '#4d7c0f',
    color_text_muted: '#5c8a14',
    color_border: '#a3e635',
    color_border_light: '#d9f99d',
    color_danger: '#ef4444',
    color_success: '#059669',
    color_primary_bg: '#f0fdf4',
    color_info_bg: '#fffbeb',
    color_danger_bg: '#fef2f2',
    color_success_bg: '#ecfdf5',
    color_warning_bg: '#fff1f2',
    font_heading: "'Georgia', 'Playfair Display', serif",
    font_body: "'Segoe UI', Roboto, sans-serif",
    font_mono: "SF Mono, Monaco, Inconsolata, 'Roboto Mono', monospace",
    heading_weight: '600',
    heading_transform: 'capitalize',
    heading_tracking: '0.02em',
    font_base_size: '16px',
    border_radius: '12px',
    border_width: '1px',
    border_width_default: '1px',
    shadow_style: 'blur',
    shadow_color: '#16a34a',
    hover_effect: 'scale',
    animation_speed: '1.3',
    animation_easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    text_inverse: '#1a2e05',
    card_frame_texture: 'none',
    card_frame_nameplate: 'banner',
    card_frame_corners: 'none',
    card_frame_foil: 'holographic',
  },

  cyberpunk: {
    color_primary: '#ff6b2b',
    color_primary_hover: '#ea580c',
    color_primary_active: '#c2410c',
    color_secondary: '#00d4ff',
    color_accent: '#a855f7',
    color_background: '#0a0a0a',
    color_surface: '#171717',
    color_surface_sunken: '#0a0a0a',
    color_surface_header: '#141414',
    color_text: '#fafafa',
    color_text_secondary: '#a3a3a3',
    color_text_muted: '#999999',
    color_border: '#ff6b2b',
    color_border_light: '#292524',
    color_danger: '#ef4444',
    color_success: '#22c55e',
    color_primary_bg: '#2a1a0f',
    color_info_bg: '#0f1a2a',
    color_danger_bg: '#2a1010',
    color_success_bg: '#0f2a10',
    color_warning_bg: '#2a1f0f',
    font_heading: "'Arial Narrow', 'Barlow Condensed', sans-serif",
    font_body: 'system-ui, -apple-system, sans-serif',
    font_mono: "SF Mono, Monaco, Inconsolata, 'Roboto Mono', monospace",
    heading_weight: '900',
    heading_transform: 'uppercase',
    heading_tracking: '0.08em',
    font_base_size: '15px',
    border_radius: '2px',
    border_width: '2px',
    border_width_default: '1px',
    shadow_style: 'glow',
    shadow_color: '#ff6b2b',
    hover_effect: 'glow',
    animation_speed: '0.7',
    animation_easing: 'cubic-bezier(0.22, 1, 0.36, 1)',
    text_inverse: '#0a0a0a',
    card_frame_texture: 'circuits',
    card_frame_nameplate: 'terminal',
    card_frame_corners: 'brackets',
    card_frame_foil: 'holographic',
  },

  'nordic-noir': {
    color_primary: '#64748b',
    color_primary_hover: '#475569',
    color_primary_active: '#334155',
    color_secondary: '#3b82f6',
    color_accent: '#d97706',
    color_background: '#f8fafc',
    color_surface: '#ffffff',
    color_surface_sunken: '#f1f5f9',
    color_surface_header: '#f8fafc',
    color_text: '#1e293b',
    color_text_secondary: '#475569',
    color_text_muted: '#708090',
    color_border: '#cbd5e1',
    color_border_light: '#e2e8f0',
    color_danger: '#dc2626',
    color_success: '#16a34a',
    color_primary_bg: '#f1f5f9',
    color_info_bg: '#eff6ff',
    color_danger_bg: '#fef2f2',
    color_success_bg: '#f0fdf4',
    color_warning_bg: '#fffbeb',
    font_heading: "'Inter', system-ui, sans-serif",
    font_body: "'Inter', system-ui, sans-serif",
    font_mono: "SF Mono, Monaco, Inconsolata, 'Roboto Mono', monospace",
    heading_weight: '500',
    heading_transform: 'none',
    heading_tracking: '-0.01em',
    font_base_size: '16px',
    border_radius: '4px',
    border_width: '1px',
    border_width_default: '1px',
    shadow_style: 'blur',
    shadow_color: '#64748b',
    hover_effect: 'scale',
    animation_speed: '1.2',
    animation_easing: 'ease-in-out',
    text_inverse: '#f8fafc',
    card_frame_texture: 'none',
    card_frame_nameplate: 'banner',
    card_frame_corners: 'none',
    card_frame_foil: 'holographic',
  },

  'deep-space-horror': {
    color_primary: '#00cc88',
    color_primary_hover: '#00b377',
    color_primary_active: '#009966',
    color_secondary: '#00ccff',
    color_accent: '#ff6633',
    color_background: '#050508',
    color_surface: '#0c0c14',
    color_surface_sunken: '#030306',
    color_surface_header: '#0a0a12',
    color_text: '#c8d0d8',
    color_text_secondary: '#7888a0',
    color_text_muted: '#80a0c0',
    color_border: '#1a2030',
    color_border_light: '#141820',
    color_danger: '#ff3344',
    color_success: '#00cc88',
    color_primary_bg: '#0a1a14',
    color_info_bg: '#0a1420',
    color_danger_bg: '#200a0c',
    color_success_bg: '#0a200e',
    color_warning_bg: '#201a0a',
    font_heading: "'Space Mono', 'Courier New', monospace",
    font_body: 'system-ui, -apple-system, sans-serif',
    font_mono: "SF Mono, Monaco, Inconsolata, 'Roboto Mono', monospace",
    heading_weight: '700',
    heading_transform: 'uppercase',
    heading_tracking: '0.12em',
    font_base_size: '15px',
    border_radius: '0',
    border_width: '1px',
    border_width_default: '1px',
    shadow_style: 'glow',
    shadow_color: '#00cc88',
    hover_effect: 'glow',
    animation_speed: '1.8',
    animation_easing: 'ease-in',
    text_inverse: '#050508',
    card_frame_texture: 'scanlines',
    card_frame_nameplate: 'readout',
    card_frame_corners: 'crosshairs',
    card_frame_foil: 'phosphor',
  },

  'arc-raiders': {
    color_primary: '#C08A10',
    color_primary_hover: '#A87700',
    color_primary_active: '#8F6600',
    color_secondary: '#2B5BA8',
    color_accent: '#B84D1A',
    color_background: '#ECE2D0',
    color_surface: '#F5EDE0',
    color_surface_sunken: '#E0D4BE',
    color_surface_header: '#F0E8D8',
    color_text: '#130918',
    color_text_secondary: '#3D2E47',
    color_text_muted: '#7A6B85',
    color_border: '#8B7D6B',
    color_border_light: '#C9BBAA',
    color_danger: '#C42B1C',
    color_success: '#2D7A3A',
    color_primary_bg: '#FFFFFF',
    color_info_bg: '#EEF1F8',
    color_danger_bg: '#FDF0EE',
    color_success_bg: '#EFF8F0',
    color_warning_bg: '#FFF5E6',
    font_heading: "'Barlow', 'Arial Narrow', sans-serif",
    font_body: 'system-ui, -apple-system, sans-serif',
    font_mono: "SF Mono, Monaco, Inconsolata, 'Roboto Mono', monospace",
    heading_weight: '800',
    heading_transform: 'uppercase',
    heading_tracking: '0.06em',
    font_base_size: '16px',
    border_radius: '4px',
    border_width: '2px',
    border_width_default: '2px',
    shadow_style: 'offset',
    shadow_color: '#8B7D6B',
    hover_effect: 'translate',
    animation_speed: '0.9',
    animation_easing: 'ease-out',
    text_inverse: '#FFFFFF',
    card_frame_texture: 'rivets',
    card_frame_nameplate: 'plate',
    card_frame_corners: 'bolts',
    card_frame_foil: 'patina',
  },

  'illuminated-literary': {
    color_primary: '#1E3A8A',
    color_primary_hover: '#1A3278',
    color_primary_active: '#152A66',
    color_secondary: '#7B2D8E',
    color_accent: '#B8860B',
    color_background: '#F5E6CC',
    color_surface: '#FAF3E6',
    color_surface_sunken: '#EDE0C8',
    color_surface_header: '#F7EDD8',
    color_text: '#1C1008',
    color_text_secondary: '#3A2A18',
    color_text_muted: '#7A6B55',
    color_border: '#8B7D6B',
    color_border_light: '#C9BBAA',
    color_danger: '#9B111E',
    color_success: '#2D6B3A',
    color_primary_bg: '#EEF1F8',
    color_info_bg: '#F0ECF5',
    color_danger_bg: '#FDF0EE',
    color_success_bg: '#EFF8F0',
    color_warning_bg: '#FFF5E6',
    font_heading: "'Libre Baskerville', Baskerville, Georgia, serif",
    font_body: 'system-ui, -apple-system, sans-serif',
    font_mono: "SF Mono, Monaco, Inconsolata, 'Roboto Mono', monospace",
    heading_weight: '700',
    heading_transform: 'none',
    heading_tracking: '0.02em',
    font_base_size: '16px',
    border_radius: '3px',
    border_width: '1px',
    border_width_default: '1px',
    shadow_style: 'blur',
    shadow_color: '#8B7D6B88',
    hover_effect: 'glow',
    animation_speed: '1.1',
    animation_easing: 'ease-in-out',
    text_inverse: '#FFFFFF',
    card_frame_texture: 'illumination',
    card_frame_nameplate: 'cartouche',
    card_frame_corners: 'floral',
    card_frame_foil: 'gilded',
  },

  'deep-fried-horror': {
    color_primary: '#FF00FF',
    color_primary_hover: '#CC00CC',
    color_primary_active: '#990099',
    color_secondary: '#00FFFF',
    color_accent: '#FF0000',
    color_background: '#FFFF00',
    color_surface: '#FFFFFF',
    color_surface_sunken: '#EEEEEE',
    color_surface_header: '#FFFF00',
    color_text: '#000000',
    color_text_secondary: '#333333',
    color_text_muted: '#666666',
    color_border: '#000000',
    color_border_light: '#CCCCCC',
    color_danger: '#FF0000',
    color_success: '#00FF00',
    color_primary_bg: '#FF00FF22',
    color_info_bg: '#00FFFF22',
    color_danger_bg: '#FF000022',
    color_success_bg: '#00FF0022',
    color_warning_bg: '#FFFF0022',
    font_heading: "'Comic Sans MS', cursive",
    font_body: "'Courier New', Courier, monospace",
    font_mono: "SF Mono, Monaco, Inconsolata, 'Roboto Mono', monospace",
    heading_weight: '900',
    heading_transform: 'uppercase',
    heading_tracking: '0.2em',
    font_base_size: '16px',
    border_radius: '0',
    border_width: '3px',
    border_width_default: '3px',
    shadow_style: 'offset',
    shadow_color: '#FF0000',
    hover_effect: 'translate',
    animation_speed: '2.0',
    animation_easing: 'steps(4, end)',
    text_inverse: '#FFFFFF',
    card_frame_texture: 'none',
    card_frame_nameplate: 'terminal',
    card_frame_corners: 'none',
    card_frame_foil: 'holographic',
  },
};

/** Maps SimulationTheme types to suggested preset names. */
export function getPresetForTheme(theme: SimulationTheme, slug?: string): ThemePresetName {
  if (slug === 'spengbabs-whore-house') return 'deep-fried-horror';

  switch (theme) {
    case 'dystopian':
      return 'cyberpunk';
    case 'utopian':
      return 'illuminated-literary';
    case 'fantasy':
      return 'sunless-sea';
    case 'scifi':
      return 'cyberpunk';
    case 'historical':
      return 'nordic-noir';
    default:
      return 'brutalist';
  }
}

/** All available preset names for UI display. */
export const PRESET_NAMES: ThemePresetName[] = [
  'brutalist',
  'sunless-sea',
  'solarpunk',
  'cyberpunk',
  'nordic-noir',
  'deep-space-horror',
  'arc-raiders',
  'illuminated-literary',
  'deep-fried-horror',
];
