import { localized, msg } from '@lit/localize';
import { css, html, LitElement, nothing } from 'lit';
import { customElement, state } from 'lit/decorators.js';
import { appState } from '../../services/AppStateManager.js';
import { simulationsApi } from '../../services/api/SimulationsApiService.js';
import { resonanceApi } from '../../services/api/index.js';
import type { Resonance, Simulation } from '../../types/index.js';
import { icons } from '../../utils/icons.js';

import { getPlatformPullQuotes } from './LoreScroll.js';
import './SimulationCard.js';
import './LoreScroll.js';
import '../resonance/ResonanceMonitor.js';

/**
 * Hero background image path in simulation.assets bucket.
 * Generated by scripts/generate_dashboard_images.py
 */
const HERO_IMAGE_PATH = '/storage/v1/object/public/simulation.assets/platform/dashboard-hero.avif';

@localized()
@customElement('velg-simulations-dashboard')
export class VelgSimulationsDashboard extends LitElement {
  static styles = css`
    :host {
      display: block;
      background: var(--color-gray-950);
      color: #fff;
      min-height: calc(100vh - var(--header-height));
    }

    /* ── Hero ── */

    .hero {
      position: relative;
      min-height: 340px;
      display: flex;
      align-items: center;
      justify-content: center;
      overflow: hidden;
      border-bottom: 2px solid var(--color-gray-700);
    }

    .hero__bg {
      position: absolute;
      inset: 0;
      animation: hero-drift 30s ease-in-out infinite alternate;
    }

    .hero__bg--image {
      width: 100%;
      height: 100%;
      object-fit: cover;
      object-position: center;
      filter: brightness(0.35);
    }

    @keyframes hero-drift {
      0% { transform: scale(1); }
      100% { transform: scale(1.06); }
    }

    .hero__bg--fallback {
      background: linear-gradient(
        135deg,
        var(--color-gray-900) 0%,
        var(--color-gray-800) 50%,
        var(--color-gray-900) 100%
      );
    }

    .hero__noise {
      position: absolute;
      inset: 0;
      opacity: 0.08;
      background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E");
      background-size: 128px 128px;
      pointer-events: none;
    }

    .hero__overlay {
      position: relative;
      z-index: 1;
      text-align: center;
      max-width: 680px;
      padding: var(--space-10) var(--space-6);
    }

    .hero__title {
      font-family: var(--font-bureau);
      font-weight: var(--font-bold);
      font-size: var(--text-4xl);
      letter-spacing: 2px;
      color: #fff;
      margin: 0 0 var(--space-5);
      text-shadow: 2px 2px 0 rgba(0, 0, 0, 0.8);
    }

    .hero__lore {
      font-family: var(--font-bureau);
      font-size: var(--text-base);
      line-height: var(--leading-relaxed);
      color: rgba(255, 255, 255, 0.6);
      margin: 0;
      font-style: italic;
    }

    /* ── Lore Strip ── */

    .lore-strip {
      background: rgba(0, 0, 0, 0.5);
      border-bottom: 1px solid var(--color-gray-700);
      padding: var(--space-2) var(--space-4);
      overflow: hidden;
    }

    .lore-strip__text {
      display: block;
      font-family: var(--font-mono);
      font-size: var(--text-xs);
      letter-spacing: var(--tracking-wider);
      text-transform: uppercase;
      color: rgba(255, 255, 255, 0.35);
      text-align: center;
      white-space: nowrap;
    }

    /* ── Content Area (padded) ── */

    .content {
      padding: var(--space-8) var(--space-6);
    }

    /* ── Shards Header ── */

    .shards-header {
      display: flex;
      align-items: center;
      gap: var(--space-3);
      margin-bottom: var(--space-6);
    }

    .shards-header__title {
      font-family: var(--font-brutalist);
      font-weight: var(--font-black);
      font-size: var(--text-xl);
      text-transform: uppercase;
      letter-spacing: var(--tracking-brutalist);
      color: #fff;
      margin: 0;
    }

    .shards-header__count {
      font-family: var(--font-mono);
      font-size: var(--text-sm);
      color: var(--color-gray-400);
    }

    .shards-header__spacer {
      flex: 1;
    }

    .btn-fracture {
      display: inline-flex;
      align-items: center;
      gap: var(--space-2);
      padding: var(--space-2) var(--space-4);
      font-family: var(--font-brutalist);
      font-weight: var(--font-black);
      font-size: var(--text-sm);
      text-transform: uppercase;
      letter-spacing: var(--tracking-brutalist);
      background: #fff;
      color: var(--color-gray-900);
      border: 2px solid #fff;
      border-radius: var(--border-radius);
      box-shadow: 4px 4px 0 rgba(255, 255, 255, 0.2);
      cursor: pointer;
      transition: all var(--transition-fast);
      flex-shrink: 0;
    }

    .btn-fracture:hover {
      transform: translate(-2px, -2px);
      box-shadow: 6px 6px 0 rgba(255, 255, 255, 0.25);
    }

    .btn-fracture:active {
      transform: translate(0);
      box-shadow: 2px 2px 0 rgba(255, 255, 255, 0.15);
    }

    /* ── Shard Grid ── */

    .shards-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
      gap: var(--space-6);
    }

    @media (max-width: 480px) {
      .shards-grid {
        grid-template-columns: 1fr;
      }
    }

    /* ── Footer Lore ── */

    .footer-lore {
      margin-top: var(--space-10);
      padding: var(--space-6) 0 var(--space-4);
      text-align: center;
      font-family: var(--font-bureau);
      font-size: var(--text-sm);
      font-style: italic;
      color: var(--color-gray-500);
      letter-spacing: var(--tracking-wide);
    }

    /* ── Tremor Warning Banner ── */

    .tremor-banner {
      display: flex;
      align-items: center;
      gap: var(--space-3);
      padding: var(--space-3) var(--space-4);
      background: rgba(239, 68, 68, 0.08);
      border-bottom: 2px solid rgba(239, 68, 68, 0.3);
      font-family: var(--font-brutalist);
      font-size: var(--text-sm);
      color: rgba(239, 68, 68, 0.9);
      text-transform: uppercase;
      letter-spacing: var(--tracking-wider);
      animation: banner-pulse 3s ease-in-out infinite;
    }

    .tremor-banner__icon {
      flex-shrink: 0;
      animation: tremor-shake 2s ease-in-out infinite;
    }

    .tremor-banner__count {
      font-weight: var(--font-bold);
      color: #ef4444;
    }

    @keyframes banner-pulse {
      0%, 100% { background: rgba(239, 68, 68, 0.08); }
      50% { background: rgba(239, 68, 68, 0.04); }
    }

    @keyframes tremor-shake {
      0%, 100% { transform: translateX(0); }
      25% { transform: translateX(-1px); }
      75% { transform: translateX(1px); }
    }

    /* ── Resonance Monitor Section ── */

    .resonance-section {
      padding: var(--space-6) var(--space-6) 0;
    }

    @media (max-width: 640px) {
      .resonance-section {
        padding: var(--space-4) var(--space-3) 0;
      }
    }

    /* ── States ── */

    .loading-state {
      display: flex;
      align-items: center;
      justify-content: center;
      min-height: 40vh;
      font-family: var(--font-brutalist);
      font-weight: var(--font-bold);
      font-size: var(--text-lg);
      text-transform: uppercase;
      letter-spacing: var(--tracking-brutalist);
      color: var(--color-gray-400);
    }

    .empty-state {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      min-height: 30vh;
      gap: var(--space-4);
      text-align: center;
      padding: var(--space-8) var(--space-6);
    }

    .empty-state__title {
      font-family: var(--font-brutalist);
      font-weight: var(--font-black);
      font-size: var(--text-xl);
      text-transform: uppercase;
      letter-spacing: var(--tracking-brutalist);
      color: #fff;
    }

    .empty-state__text {
      font-size: var(--text-base);
      color: var(--color-gray-400);
      max-width: 480px;
    }

    .error-state {
      margin: var(--space-6);
      padding: var(--space-4);
      background: var(--color-danger-bg);
      border: 2px solid var(--color-danger-border);
      color: var(--color-text-danger);
      font-family: var(--font-brutalist);
      font-weight: var(--font-bold);
      font-size: var(--text-sm);
      text-transform: uppercase;
    }

    /* ── Scroll Nav (depth gauge) ── */

    .scroll-nav {
      position: fixed;
      bottom: 24px;
      right: 24px;
      z-index: 100;
      opacity: 0;
      transform: translateX(16px);
      transition: opacity 0.35s ease, transform 0.35s ease;
      pointer-events: none;
    }

    .scroll-nav--visible {
      opacity: 1;
      transform: translateX(0);
      pointer-events: auto;
    }

    .scroll-nav__btn {
      position: relative;
      width: 44px;
      height: 44px;
      border-radius: 50%;
      border: none;
      background: rgba(10, 10, 14, 0.85);
      backdrop-filter: blur(12px);
      -webkit-backdrop-filter: blur(12px);
      cursor: pointer;
      padding: 0;
      display: flex;
      align-items: center;
      justify-content: center;
      transition: box-shadow 0.25s ease, background 0.25s ease;
    }

    .scroll-nav__btn:hover {
      background: rgba(10, 10, 14, 0.95);
      box-shadow: 0 0 20px rgba(255, 200, 100, 0.15), 0 0 4px rgba(255, 200, 100, 0.1);
    }

    .scroll-nav__btn:active {
      transform: scale(0.94);
    }

    .scroll-nav__ring {
      position: absolute;
      inset: 0;
      pointer-events: none;
    }

    .scroll-nav__track {
      fill: none;
      stroke: rgba(255, 200, 100, 0.1);
      stroke-width: 1.5;
    }

    .scroll-nav__progress {
      fill: none;
      stroke: rgba(255, 200, 100, 0.55);
      stroke-width: 1.5;
      stroke-linecap: round;
      transform: rotate(-90deg);
      transform-origin: center;
      transition: stroke-dasharray 0.15s ease;
    }

    .scroll-nav__arrow {
      transition: transform 0.4s cubic-bezier(0.4, 0, 0.2, 1);
      flex-shrink: 0;
    }

    .scroll-nav__arrow--down {
      transform: rotate(180deg);
    }

    @media (prefers-reduced-motion: reduce) {
      .scroll-nav__arrow {
        transition: none;
      }

      .scroll-nav {
        transition: opacity 0.15s ease;
        transform: none;
      }

      .scroll-nav--visible {
        transform: none;
      }
    }

    /* ── Responsive ── */

    @media (max-width: 640px) {
      .hero {
        min-height: 220px;
      }

      .hero__title {
        font-size: var(--text-2xl);
        letter-spacing: 1px;
      }

      .hero__lore {
        font-size: var(--text-xs);
      }

      .hero__overlay {
        padding: var(--space-6) var(--space-4);
      }

      .content {
        padding: var(--space-4) var(--space-3);
      }

      .shards-grid {
        grid-template-columns: 1fr;
      }

      .shards-header {
        flex-wrap: wrap;
      }
    }
  `;

  @state() private _simulations: Simulation[] = [];
  @state() private _loading = true;
  @state() private _error: string | null = null;
  @state() private _activeResonances: Resonance[] = [];

  /** Scroll nav state */
  @state() private _scrollNavVisible = false;
  @state() private _scrollDirection: 'up' | 'down' = 'down';
  @state() private _scrollProgress = 0;

  private _rafId = 0;

  async connectedCallback(): Promise<void> {
    super.connectedCallback();
    window.addEventListener('scroll', this._onScroll, { passive: true });
    await Promise.all([this._loadSimulations(), this._loadActiveResonances()]);
  }

  disconnectedCallback(): void {
    super.disconnectedCallback();
    window.removeEventListener('scroll', this._onScroll);
    if (this._rafId) cancelAnimationFrame(this._rafId);
  }

  private _onScroll = () => {
    if (this._rafId) return;
    this._rafId = requestAnimationFrame(() => {
      const scrollY = window.scrollY;
      const docHeight = document.documentElement.scrollHeight - window.innerHeight;
      this._scrollNavVisible = scrollY > 120;
      this._scrollDirection = scrollY < 300 ? 'down' : 'up';
      this._scrollProgress = docHeight > 0 ? Math.min(scrollY / docHeight, 1) : 0;
      this._rafId = 0;
    });
  };

  private _handleScrollNav(): void {
    if (this._scrollDirection === 'up') {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    } else {
      window.scrollTo({ top: document.documentElement.scrollHeight, behavior: 'smooth' });
    }
  }

  private async _loadSimulations(): Promise<void> {
    this._loading = true;
    this._error = null;

    try {
      const response = await simulationsApi.list();
      const items = Array.isArray(response.data) ? response.data : [];
      if (response.success) {
        this._simulations = items;
        appState.setSimulations(items);
      } else {
        this._error = response.error?.message || msg('Failed to load simulations.');
      }
    } catch {
      this._error = msg('An unexpected error occurred while loading simulations.');
    } finally {
      this._loading = false;
    }
  }

  private async _loadActiveResonances(): Promise<void> {
    try {
      const res = await resonanceApi.list({ limit: '10' });
      if (res.success && res.data) {
        this._activeResonances = (res.data as Resonance[]).filter(
          (r) => r.status === 'detected' || r.status === 'impacting',
        );
      }
    } catch {
      // Non-critical — silently ignore
    }
  }

  private _handleCreateClick(): void {
    this.dispatchEvent(
      new CustomEvent('navigate', {
        detail: '/new-simulation',
        bubbles: true,
        composed: true,
      }),
    );
  }

  private _handleSimulationClick(e: CustomEvent<Simulation>): void {
    const simulation = e.detail;
    appState.setCurrentSimulation(simulation);
    window.history.pushState({}, '', `/simulations/${simulation.slug}/lore`);
    window.dispatchEvent(new PopStateEvent('popstate'));
  }

  private _getHeroImageUrl(): string | null {
    const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
    if (!supabaseUrl) return null;
    return `${supabaseUrl}${HERO_IMAGE_PATH}`;
  }

  protected render() {
    if (this._loading) {
      return html`<div class="loading-state">${msg('Loading Simulations...')}</div>`;
    }

    if (this._error) {
      return html`<div class="error-state">${this._error}</div>`;
    }

    const heroUrl = this._getHeroImageUrl();
    const count = this._simulations.length;

    return html`
      <!-- Hero -->
      <section class="hero">
        ${
          heroUrl
            ? html`<img
              class="hero__bg hero__bg--image"
              src=${heroUrl}
              fetchpriority="high"
              decoding="async"
              alt=""
              @error=${(e: Event) => { (e.target as HTMLImageElement).replaceWith(Object.assign(document.createElement('div'), { className: 'hero__bg hero__bg--fallback' })); }}
            />`
            : html`<div class="hero__bg hero__bg--fallback"></div>`
        }
        <div class="hero__noise"></div>
        <div class="hero__overlay">
          <h1 class="hero__title">${msg('Shattered Worlds. Bleeding Borders.')}</h1>
          <p class="hero__lore">
            ${msg('There was once a single world. It broke into shards — each a complete reality with its own physics, its own history, its own answer to a question the universe could not ask in one voice. The edges do not fit together. But they do touch.')}
          </p>
        </div>
      </section>

      <!-- Lore Strip -->
      <div class="lore-strip">
        <span class="lore-strip__text">
          // ${msg('Bureau of Impossible Geography — Mapping the spaces between realities since the Fracture')} //
        </span>
      </div>

      <!-- Tremor Warning Banner -->
      ${this._activeResonances.length > 0
        ? html`
          <div class="tremor-banner" role="alert">
            <span class="tremor-banner__icon" aria-hidden="true">${icons.substrateTremor(18)}</span>
            <span class="tremor-banner__count">${this._activeResonances.length}</span>
            ${msg('substrate tremors detected — the space between worlds is afraid')}
          </div>
        `
        : nothing}

      <!-- Lore Scroll -->
      <velg-lore-scroll .pullQuotes=${getPlatformPullQuotes()}></velg-lore-scroll>

      <!-- Resonance Monitor -->
      ${this._activeResonances.length > 0
        ? html`
          <section class="resonance-section">
            <resonance-monitor></resonance-monitor>
          </section>
        `
        : nothing}

      <!-- Shards -->
      ${
        count === 0
          ? html`
          <div class="empty-state">
            <div class="empty-state__title">${msg('No Shards Yet')}</div>
            <div class="empty-state__text">
              ${msg('Fracture reality and create your first shard — a world with its own agents, buildings, and events.')}
            </div>
            ${
              appState.isAuthenticated.value
                ? html`
              <button class="btn-fracture" @click=${this._handleCreateClick}>
                ${msg('Fracture a New Shard')}
              </button>
            `
                : null
            }
          </div>
        `
          : html`
          <div class="content">
            <div class="shards-header">
              <h2 class="shards-header__title">${msg('Active Shards')}</h2>
              <span class="shards-header__count">${count} ${msg('worlds')}</span>
              <div class="shards-header__spacer"></div>
              ${
                appState.isAuthenticated.value
                  ? html`
                <button class="btn-fracture" @click=${this._handleCreateClick}>
                  ${msg('Fracture a New Shard')}
                </button>
              `
                  : null
              }
            </div>

            <div class="shards-grid">
              ${this._simulations.map(
                (sim, i) => html`
                  <velg-simulation-card
                    style="--i: ${i}"
                    .simulation=${sim}
                    @simulation-click=${this._handleSimulationClick}
                  ></velg-simulation-card>
                `,
              )}
            </div>

            <div class="footer-lore">
              ${msg('The map is open. The Shards are waiting. The Cartographers are watching. Which world do you enter first?')}
            </div>
          </div>
        `
      }

      ${this._renderScrollNav()}
    `;
  }

  private _renderScrollNav() {
    if (this._loading) return nothing;
    const circ = 2 * Math.PI * 19;
    const dash = this._scrollProgress * circ;
    const isUp = this._scrollDirection === 'up';

    return html`
      <div class="scroll-nav ${this._scrollNavVisible ? 'scroll-nav--visible' : ''}">
        <button
          class="scroll-nav__btn"
          @click=${this._handleScrollNav}
          aria-label=${isUp ? msg('Scroll to top') : msg('Scroll to bottom')}
        >
          <svg class="scroll-nav__ring" viewBox="0 0 44 44">
            <circle class="scroll-nav__track" cx="22" cy="22" r="19" />
            <circle
              class="scroll-nav__progress"
              cx="22" cy="22" r="19"
              stroke-dasharray="${dash} ${circ - dash}"
            />
          </svg>
          <svg
            class="scroll-nav__arrow ${isUp ? '' : 'scroll-nav__arrow--down'}"
            width="16" height="16" viewBox="0 0 16 16"
            fill="none" aria-hidden="true"
          >
            <path d="M8 3 L13 9 L11.5 10.2 L8.75 7V13H7.25V7L4.5 10.2 L3 9 L8 3Z"
              fill="rgba(255, 200, 100, 0.75)" />
          </svg>
        </button>
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'velg-simulations-dashboard': VelgSimulationsDashboard;
  }
}
