import { localized, msg } from '@lit/localize';
import { css, html, LitElement } from 'lit';
import { customElement, state } from 'lit/decorators.js';
import { appState } from '../../services/AppStateManager.js';
import { simulationsApi } from '../../services/api/SimulationsApiService.js';
import type { Simulation } from '../../types/index.js';

import './SimulationCard.js';
import './LoreScroll.js';

/**
 * Hero background image path in simulation.assets bucket.
 * Generated by scripts/generate_dashboard_images.py
 */
const HERO_IMAGE_PATH = '/storage/v1/object/public/simulation.assets/platform/dashboard-hero.webp';

@localized()
@customElement('velg-simulations-dashboard')
export class VelgSimulationsDashboard extends LitElement {
  static styles = css`
    :host {
      display: block;
      background: var(--color-gray-950);
      color: #fff;
      min-height: calc(100vh - var(--header-height));
    }

    /* ── Hero ── */

    .hero {
      position: relative;
      min-height: 340px;
      display: flex;
      align-items: center;
      justify-content: center;
      overflow: hidden;
      border-bottom: 2px solid var(--color-gray-700);
    }

    .hero__bg {
      position: absolute;
      inset: 0;
      background-size: cover;
      background-position: center;
      animation: hero-drift 30s ease-in-out infinite alternate;
    }

    .hero__bg--has-image {
      filter: brightness(0.35);
    }

    @keyframes hero-drift {
      0% { transform: scale(1); }
      100% { transform: scale(1.06); }
    }

    .hero__bg--fallback {
      background: linear-gradient(
        135deg,
        var(--color-gray-900) 0%,
        var(--color-gray-800) 50%,
        var(--color-gray-900) 100%
      );
    }

    .hero__noise {
      position: absolute;
      inset: 0;
      opacity: 0.08;
      background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E");
      background-size: 128px 128px;
      pointer-events: none;
    }

    .hero__overlay {
      position: relative;
      z-index: 1;
      text-align: center;
      max-width: 680px;
      padding: var(--space-10) var(--space-6);
    }

    .hero__title {
      font-family: var(--font-brutalist);
      font-weight: var(--font-black);
      font-size: var(--text-4xl);
      text-transform: uppercase;
      letter-spacing: 4px;
      color: #fff;
      margin: 0 0 var(--space-5);
      text-shadow: 2px 2px 0 rgba(0, 0, 0, 0.8);
    }

    .hero__lore {
      font-family: var(--font-mono);
      font-size: var(--text-sm);
      line-height: var(--leading-relaxed);
      color: rgba(255, 255, 255, 0.6);
      margin: 0;
      font-style: italic;
    }

    /* ── Lore Strip ── */

    .lore-strip {
      background: rgba(0, 0, 0, 0.5);
      border-bottom: 1px solid var(--color-gray-700);
      padding: var(--space-2) var(--space-4);
      overflow: hidden;
    }

    .lore-strip__text {
      display: block;
      font-family: var(--font-mono);
      font-size: var(--text-xs);
      letter-spacing: var(--tracking-wider);
      text-transform: uppercase;
      color: rgba(255, 255, 255, 0.35);
      text-align: center;
      white-space: nowrap;
    }

    /* ── Content Area (padded) ── */

    .content {
      padding: var(--space-8) var(--space-6);
    }

    /* ── Shards Header ── */

    .shards-header {
      display: flex;
      align-items: center;
      gap: var(--space-3);
      margin-bottom: var(--space-6);
    }

    .shards-header__title {
      font-family: var(--font-brutalist);
      font-weight: var(--font-black);
      font-size: var(--text-xl);
      text-transform: uppercase;
      letter-spacing: var(--tracking-brutalist);
      color: #fff;
      margin: 0;
    }

    .shards-header__count {
      font-family: var(--font-mono);
      font-size: var(--text-sm);
      color: var(--color-gray-400);
    }

    .shards-header__spacer {
      flex: 1;
    }

    .btn-fracture {
      display: inline-flex;
      align-items: center;
      gap: var(--space-2);
      padding: var(--space-2) var(--space-4);
      font-family: var(--font-brutalist);
      font-weight: var(--font-black);
      font-size: var(--text-sm);
      text-transform: uppercase;
      letter-spacing: var(--tracking-brutalist);
      background: #fff;
      color: var(--color-gray-900);
      border: 2px solid #fff;
      border-radius: var(--border-radius);
      box-shadow: 4px 4px 0 rgba(255, 255, 255, 0.2);
      cursor: pointer;
      transition: all var(--transition-fast);
      flex-shrink: 0;
    }

    .btn-fracture:hover {
      transform: translate(-2px, -2px);
      box-shadow: 6px 6px 0 rgba(255, 255, 255, 0.25);
    }

    .btn-fracture:active {
      transform: translate(0);
      box-shadow: 2px 2px 0 rgba(255, 255, 255, 0.15);
    }

    /* ── Shard Grid ── */

    .shards-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(380px, 1fr));
      gap: var(--space-6);
    }

    /* ── Footer Lore ── */

    .footer-lore {
      margin-top: var(--space-10);
      padding: var(--space-6) 0 var(--space-4);
      text-align: center;
      font-family: var(--font-mono);
      font-size: var(--text-xs);
      font-style: italic;
      color: var(--color-gray-500);
      letter-spacing: var(--tracking-wide);
    }

    /* ── States ── */

    .loading-state {
      display: flex;
      align-items: center;
      justify-content: center;
      min-height: 40vh;
      font-family: var(--font-brutalist);
      font-weight: var(--font-bold);
      font-size: var(--text-lg);
      text-transform: uppercase;
      letter-spacing: var(--tracking-brutalist);
      color: var(--color-gray-400);
    }

    .empty-state {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      min-height: 30vh;
      gap: var(--space-4);
      text-align: center;
      padding: var(--space-8) var(--space-6);
    }

    .empty-state__title {
      font-family: var(--font-brutalist);
      font-weight: var(--font-black);
      font-size: var(--text-xl);
      text-transform: uppercase;
      letter-spacing: var(--tracking-brutalist);
      color: #fff;
    }

    .empty-state__text {
      font-size: var(--text-base);
      color: var(--color-gray-400);
      max-width: 480px;
    }

    .error-state {
      margin: var(--space-6);
      padding: var(--space-4);
      background: var(--color-danger-bg);
      border: 2px solid var(--color-danger-border);
      color: var(--color-text-danger);
      font-family: var(--font-brutalist);
      font-weight: var(--font-bold);
      font-size: var(--text-sm);
      text-transform: uppercase;
    }

    /* ── Responsive ── */

    @media (max-width: 640px) {
      .hero {
        min-height: 240px;
      }

      .hero__title {
        font-size: var(--text-2xl);
        letter-spacing: 2px;
      }

      .content {
        padding: var(--space-5) var(--space-4);
      }

      .shards-grid {
        grid-template-columns: 1fr;
      }

      .shards-header {
        flex-wrap: wrap;
      }
    }
  `;

  @state() private _simulations: Simulation[] = [];
  @state() private _loading = true;
  @state() private _error: string | null = null;

  async connectedCallback(): Promise<void> {
    super.connectedCallback();
    await this._loadSimulations();
  }

  private async _loadSimulations(): Promise<void> {
    this._loading = true;
    this._error = null;

    try {
      const response = await simulationsApi.list();
      const items = Array.isArray(response.data) ? response.data : [];
      if (response.success && items.length > 0) {
        this._simulations = items;
        appState.setSimulations(items);
      } else {
        this._error = response.error?.message || msg('Failed to load simulations.');
      }
    } catch {
      this._error = msg('An unexpected error occurred while loading simulations.');
    } finally {
      this._loading = false;
    }
  }

  private _handleCreateClick(): void {
    this.dispatchEvent(
      new CustomEvent('navigate', {
        detail: '/new-simulation',
        bubbles: true,
        composed: true,
      }),
    );
  }

  private _handleSimulationClick(e: CustomEvent<Simulation>): void {
    const simulation = e.detail;
    appState.setCurrentSimulation(simulation);
    window.history.pushState({}, '', `/simulations/${simulation.id}/agents`);
    window.dispatchEvent(new PopStateEvent('popstate'));
  }

  private _getHeroImageUrl(): string | null {
    const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
    if (!supabaseUrl) return null;
    return `${supabaseUrl}${HERO_IMAGE_PATH}`;
  }

  protected render() {
    if (this._loading) {
      return html`<div class="loading-state">${msg('Loading Simulations...')}</div>`;
    }

    if (this._error) {
      return html`<div class="error-state">${this._error}</div>`;
    }

    const heroUrl = this._getHeroImageUrl();
    const count = this._simulations.length;

    return html`
      <!-- Hero -->
      <section class="hero">
        <div
          class="hero__bg ${heroUrl ? 'hero__bg--has-image' : 'hero__bg--fallback'}"
          style=${heroUrl ? `background-image: url(${heroUrl})` : ''}
        ></div>
        <div class="hero__noise"></div>
        <div class="hero__overlay">
          <h1 class="hero__title">${msg("The Cartographer's Map")}</h1>
          <p class="hero__lore">
            ${msg("There was once a single world. Something broke it into shards. Each shard runs on its own rules, its own physics of power. The edges don't quite fit together anymore. But they do touch.")}
          </p>
        </div>
      </section>

      <!-- Lore Strip -->
      <div class="lore-strip">
        <span class="lore-strip__text">
          // ${msg('The Bleed — Where shards press against each other, reality thins')} //
        </span>
      </div>

      <!-- Lore Scroll -->
      <velg-lore-scroll></velg-lore-scroll>

      <!-- Shards -->
      ${
        count === 0
          ? html`
          <div class="empty-state">
            <div class="empty-state__title">${msg('No Shards Yet')}</div>
            <div class="empty-state__text">
              ${msg('Fracture reality and create your first shard — a world with its own agents, buildings, and events.')}
            </div>
            <button class="btn-fracture" @click=${this._handleCreateClick}>
              ${msg('Fracture a New Shard')}
            </button>
          </div>
        `
          : html`
          <div class="content">
            <div class="shards-header">
              <h2 class="shards-header__title">${msg('Active Shards')}</h2>
              <span class="shards-header__count">${count} ${msg('worlds')}</span>
              <div class="shards-header__spacer"></div>
              <button class="btn-fracture" @click=${this._handleCreateClick}>
                ${msg('Fracture a New Shard')}
              </button>
            </div>

            <div class="shards-grid">
              ${this._simulations.map(
                (sim) => html`
                  <velg-simulation-card
                    .simulation=${sim}
                    @simulation-click=${this._handleSimulationClick}
                  ></velg-simulation-card>
                `,
              )}
            </div>

            <div class="footer-lore">
              ${msg('The map is open. The Shards are waiting. The Cartographers are watching. They always are.')}
            </div>
          </div>
        `
      }
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'velg-simulations-dashboard': VelgSimulationsDashboard;
  }
}
